biobank_structures_dict = {'left_thalamus': 10,
                           'left_caudate': 11,
                           'left_putamen': 12,
                           'left_pallidum': 13,
                           'brain_stem': 16,
                           'left_hippocampus': 17,
                           'left_amygdala': 18,
                           'left_accumbens': 26,
                           'right_thalamus': 49,
                           'right_caudate': 50,
                           'right_putamen': 51,
                           'right_pallidum': 52,
                           'right_hippocampus': 53,
                           'right_amygdala': 54,
                           'right_accumbens': 58}
