structures_dict_04 = {'cortex': 1,
                      'subcortical_grey_matter': 2,
                      'white_matter': 3,
                      'CSF': 4}

structures_dict_24 = {'left_cerebral_white_matter': 1,
                      'left_cerebral_cortex': 2,
                      'left_lateral_ventricle': 3,
                      'left_inf_lateral_ventricle': 4,
                      'left_thalamus': 5,
                      'left_caudate': 6,
                      'left_putamen': 7,
                      'left_pallidum': 8,
                      '3rd_ventricle': 9,
                      'brain_stem': 10,
                      'left_hippocampus': 11,
                      'left_ventral_dorsal_cord': 12,
                      'left choroid_plexus': 13,
                      'right_cerebral_white_matter': 14,
                      'right_cerebral_cortex': 15,
                      'right_lateral_ventricle': 16,
                      'right_inf_lateral_ventricle': 17,
                      'right_thalamus': 18,
                      'right_caudate': 19,
                      'right_putamen': 20,
                      'right_pallidum': 21,
                      'right_hippocampus': 22,
                      'right_ventrcal_dorsal_cord': 23,
                      'right_choroid_plexus': 24}

structures_dict_35 = {'left_cerebral_white_matter': 1,
                      'left_cerebral_cortex': 2,
                      'left_lateral_ventricle': 3,
                      'left_inf_lateral_ventricle': 4,
                      'left_cerebellum_white_matter': 5,
                      'left_cerebellum_cortex': 6,
                      'left_thalamus': 7,
                      'left_caudate': 8,
                      'left_putamen': 9,
                      'left_pallidum': 10,
                      '3rd_ventricle': 11,
                      '4th_ventricle': 12,
                      'brain_stem': 13,
                      'left_hippocampus': 14,
                      'left_amygdala': 15,
                      'left_accumbens': 16,
                      'left_ventral_dorsal_cord': 17,
                      'left_vessel': 18,
                      'left_choroid_plexus': 19,
                      'right_cerebral_white_matter': 20,
                      'right_cerebral_cortex': 21,
                      'right_lateral_ventricle': 22,
                      'right_inf_lateral_ventricle': 23,
                      'right_cerebellum_white_matter': 24,
                      'right_cerebellum_cortex': 25,
                      'right_thalamus': 26,
                      'right_caudate': 27,
                      'right_putamen': 28,
                      'right_pallidum': 29,
                      'right_hippocampus': 30,
                      'right_amygdala': 31,
                      'right_accumbens': 32,
                      'right_ventral_dorsal_cord': 33,
                      'right_vessel': 34,
                      'right_choroid_plexus': 35}

structures_dict_RGB = {'left_cerebral_white_matter': [0, 245, 245, 245],
                       'left_cerebral_cortex': [0, 20, 62, 78],
                       'left_lateral_ventricle': [0, 120, 18, 134],
                       'left_inf_lateral_ventricle': [0, 196, 58, 250],
                       'left_cerebellum_white_matter': [0, 220, 248, 164],
                       'left_cerebellum_cortex': [0, 230, 148, 34],
                       'left_thalamus': [0, 0, 118, 14],
                       'left_caudate': [0, 122, 186, 220],
                       'left_putamen': [0, 236, 13, 176],
                       'left_pallidum': [0, 12, 40, 255],
                       '3rd_ventricle': [0, 20, 182, 142],
                       '4th_ventricle': [0, 42, 20, 164],
                       'brain_stem': [0, 119, 159, 176],
                       'left_hippocampus': [0, 220, 216, 20],
                       'left_amygdala': [0, 10, 255, 255],
                       'left_accumbens': [0, 255, 165, 0],
                       'left_ventral_dorsal_cord': [0, 165, 42, 42],
                       'left_vessel': [0, 130, 32, 240],
                       'left_choroid_plexus': [0, 0, 200, 200],
                       'right_cerebral_white_matter': [0, 245, 245, 245],
                       'right_cerebral_cortex': [0, 205, 62, 78],
                       'right_lateral_ventricle': [0, 120, 18, 134],
                       'right_inf_lateral_ventricle': [0, 196, 58, 250],
                       'right_cerebellum_white_matter': [0, 220, 248, 164],
                       'right_cerebellum_cortex': [0, 230, 148, 34],
                       'right_thalamus': [0, 0, 118, 14],
                       'right_caudate': [0, 122, 186, 220],
                       'right_putamen': [0, 236, 13, 176],
                       'right_pallidum': [0, 12, 48, 255],
                       'right_hippocampus': [0, 220, 216, 20],
                       'right_amygdala': [0, 103, 255, 255],
                       'right_accumbens': [0, 255, 165, 0],
                       'right_ventral_dorsal_cord': [0, 105, 42, 42],
                       'right_vessel': [0, 160, 32, 240],
                       'right_choroid_plexus': [0, 0, 200, 200]}
